name: quickcatch-frontend-ci

on:
  push:
    branches:
      - main  # main 브랜치에 push 이벤트가 발생했을 때 workflow 실행

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # job이 실행될 가상 환경의 운영체제

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # runner에 저장소 코드를 다운하고 특정 브랜치로 checkout 하는 jobs 실행

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  # Docker Buildx를 설정, Buildx는 다양한 플랫폼에 대해 이미지를 빌드할 수 있게 해줌

    - name: Log in to Docker Hub
      uses: docker/login-action@v2  # Docker Hub에 로그인
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }} 
        password: ${{ secrets.DOCKER_HUB_TOKEN }}  

    - name: Get latest Docker image version
      id: get-latest-version 
      run: |
        # Docker Hub API를 호출하여 최신 태그를 가져옴
        LATEST_TAG=$(curl -s https://hub.docker.com/v2/repositories/minho7336/qkc-app-fro/tags?page_size=1 | jq -r '.results[0].name')
        if [ -z "$LATEST_TAG" ]; then
          echo "No existing tags found. Setting latest tag to 0.0"
          LATEST_TAG="0.0"  # 기존 태그가 없으면 기본 값을 0.0으로 설정
        fi
        echo "Latest tag: $LATEST_TAG"
        echo "::set-output name=latest-tag::$LATEST_TAG"  # 최신 태그를 워크플로우 출력으로 설정

    - name: Increment version
      id: increment-version  # 이 단계의 ID를 설정하여 이후 단계에서 참조할 수 있게 함
      run: |
        # 최신 태그에서 버전 번호를 추출하고 1 증가시킵니다.
        LATEST_TAG=${{ steps.get-latest-version.outputs.latest-tag }}
        VERSION_NUMBER=$(echo $LATEST_TAG | cut -d. -f1)
        NEW_VERSION=$((VERSION_NUMBER + 1)).0
        if [ "$LATEST_TAG" = "0.0" ]; then
          NEW_VERSION="1.0"  # 최신 태그가 0.0이면 새로운 버전을 1.0으로 설정
        fi
        echo "New tag: $NEW_VERSION"
        echo "::set-output name=new-tag::$NEW_VERSION"  # 새로운 태그를 워크플로우 출력으로 설정

    - name: Build Docker image
      run: docker build . -t minho7336/qkc-app-fro:${{ steps.increment-version.outputs.new-tag }}  # 도커 이미지를 빌드하고 새로운 태그를 붙임

    - name: Push Docker image
      run: docker push minho7336/qkc-app-fro:${{ steps.increment-version.outputs.new-tag }}  # 빌드된 도커 이미지를 Docker Hub에 push
